-- CreateTable
CREATE TABLE `ConcreteCubeLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sampleId` INTEGER NULL,
    `sampleSetId` INTEGER NULL,
    `dateReceived` DATETIME(3) NULL,
    `client` VARCHAR(191) NULL,
    `project` VARCHAR(191) NULL,
    `castingDate` DATETIME(3) NULL,
    `testingDate` DATETIME(3) NULL,
    `class` VARCHAR(191) NULL,
    `ageDays` VARCHAR(191) NULL,
    `areaOfUse` VARCHAR(191) NULL,
    `sampleSerial` VARCHAR(191) NULL,
    `lengthMm` VARCHAR(191) NULL,
    `widthMm` VARCHAR(191) NULL,
    `heightMm` VARCHAR(191) NULL,
    `weightKg` VARCHAR(191) NULL,
    `machineUsed` VARCHAR(191) NULL,
    `loadkN` VARCHAR(191) NULL,
    `modeOfFailure` VARCHAR(191) NULL,
    `temperatureC` VARCHAR(191) NULL,
    `certificateNo` VARCHAR(191) NULL,
    `commentRemark` VARCHAR(191) NULL,
    `technician` VARCHAR(191) NULL,
    `dateOfIssue` DATETIME(3) NULL,
    `issueId` VARCHAR(191) NULL,
    `takenBy` VARCHAR(191) NULL,
    `dateTaken` DATETIME(3) NULL,
    `contact` VARCHAR(191) NULL,
    `receiptNo` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BricksBlocksLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sampleId` INTEGER NULL,
    `sampleSetId` INTEGER NULL,
    `dateReceived` DATETIME(3) NULL,
    `client` VARCHAR(191) NULL,
    `project` VARCHAR(191) NULL,
    `castingDate` DATETIME(3) NULL,
    `testingDate` DATETIME(3) NULL,
    `ageDays` VARCHAR(191) NULL,
    `areaOfUse` VARCHAR(191) NULL,
    `sampleSerial` VARCHAR(191) NULL,
    `sampleType` VARCHAR(191) NULL,
    `lengthMm` VARCHAR(191) NULL,
    `widthMm` VARCHAR(191) NULL,
    `heightMm` VARCHAR(191) NULL,
    `holeANo` VARCHAR(191) NULL,
    `holeALMm` VARCHAR(191) NULL,
    `holeAWMm` VARCHAR(191) NULL,
    `holeBNo` VARCHAR(191) NULL,
    `holeBLMm` VARCHAR(191) NULL,
    `holeBWMm` VARCHAR(191) NULL,
    `notchNo` VARCHAR(191) NULL,
    `notchLMm` VARCHAR(191) NULL,
    `notchWMm` VARCHAR(191) NULL,
    `weightKg` VARCHAR(191) NULL,
    `machineUsed` VARCHAR(191) NULL,
    `loadkN` VARCHAR(191) NULL,
    `modeOfFailure` VARCHAR(191) NULL,
    `temperatureC` VARCHAR(191) NULL,
    `certificateNo` VARCHAR(191) NULL,
    `commentRemark` VARCHAR(191) NULL,
    `technician` VARCHAR(191) NULL,
    `dateOfIssue` DATETIME(3) NULL,
    `issueId` VARCHAR(191) NULL,
    `takenBy` VARCHAR(191) NULL,
    `dateTaken` DATETIME(3) NULL,
    `contact` VARCHAR(191) NULL,
    `receiptNo` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PaversLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sampleId` INTEGER NULL,
    `sampleSetId` INTEGER NULL,
    `dateReceived` DATETIME(3) NULL,
    `client` VARCHAR(191) NULL,
    `project` VARCHAR(191) NULL,
    `castingDate` DATETIME(3) NULL,
    `testingDate` DATETIME(3) NULL,
    `ageDays` VARCHAR(191) NULL,
    `areaOfUse` VARCHAR(191) NULL,
    `sampleSerial` VARCHAR(191) NULL,
    `paverType` VARCHAR(191) NULL,
    `lengthMm` VARCHAR(191) NULL,
    `widthMm` VARCHAR(191) NULL,
    `heightMm` VARCHAR(191) NULL,
    `paversPerM2` VARCHAR(191) NULL,
    `areaMm2` VARCHAR(191) NULL,
    `weightKg` VARCHAR(191) NULL,
    `machineUsed` VARCHAR(191) NULL,
    `loadkN` VARCHAR(191) NULL,
    `modeOfFailure` VARCHAR(191) NULL,
    `temperatureC` VARCHAR(191) NULL,
    `certificateNo` VARCHAR(191) NULL,
    `commentRemark` VARCHAR(191) NULL,
    `technician` VARCHAR(191) NULL,
    `dateOfIssue` DATETIME(3) NULL,
    `issueId` VARCHAR(191) NULL,
    `takenBy` VARCHAR(191) NULL,
    `dateTaken` DATETIME(3) NULL,
    `contact` VARCHAR(191) NULL,
    `receiptNo` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ConcreteCylinderLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sampleId` INTEGER NULL,
    `sampleSetId` INTEGER NULL,
    `castingDate` DATETIME(3) NULL,
    `testingDate` DATETIME(3) NULL,
    `class` VARCHAR(191) NULL,
    `ageDays` VARCHAR(191) NULL,
    `areaOfUse` VARCHAR(191) NULL,
    `sampleSerial` VARCHAR(191) NULL,
    `diameterMm` VARCHAR(191) NULL,
    `heightMm` VARCHAR(191) NULL,
    `weightKg` VARCHAR(191) NULL,
    `machineUsed` VARCHAR(191) NULL,
    `loadkN` VARCHAR(191) NULL,
    `modeOfFailure` VARCHAR(191) NULL,
    `temperatureC` VARCHAR(191) NULL,
    `certificateNo` VARCHAR(191) NULL,
    `commentRemark` VARCHAR(191) NULL,
    `technician` VARCHAR(191) NULL,
    `dateOfIssue` DATETIME(3) NULL,
    `issueId` VARCHAR(191) NULL,
    `takenBy` VARCHAR(191) NULL,
    `dateTaken` DATETIME(3) NULL,
    `contact` VARCHAR(191) NULL,
    `receiptNo` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WaterAbsorptionLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sampleId` INTEGER NULL,
    `sampleSetId` INTEGER NULL,
    `dateOfReceipt` DATETIME(3) NULL,
    `client` VARCHAR(191) NULL,
    `project` VARCHAR(191) NULL,
    `castingDate` DATETIME(3) NULL,
    `testingDate` DATETIME(3) NULL,
    `ageDays` VARCHAR(191) NULL,
    `areaOfUse` VARCHAR(191) NULL,
    `sampleSerial` VARCHAR(191) NULL,
    `sampleType` VARCHAR(191) NULL,
    `lengthMm` VARCHAR(191) NULL,
    `widthMm` VARCHAR(191) NULL,
    `heightMm` VARCHAR(191) NULL,
    `ovenDriedWeightKg` VARCHAR(191) NULL,
    `weightAfterSoakingKg` VARCHAR(191) NULL,
    `waterWeightKg` VARCHAR(191) NULL,
    `waterAbsorptionPct` VARCHAR(191) NULL,
    `certificateNo` VARCHAR(191) NULL,
    `commentRemark` VARCHAR(191) NULL,
    `technician` VARCHAR(191) NULL,
    `dateOfIssue` DATETIME(3) NULL,
    `issueId` VARCHAR(191) NULL,
    `takenBy` VARCHAR(191) NULL,
    `dateTaken` DATETIME(3) NULL,
    `contact` VARCHAR(191) NULL,
    `receiptNo` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ProjectsLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sampleId` INTEGER NULL,
    `sampleSetId` INTEGER NULL,
    `date` DATETIME(3) NULL,
    `bigProjectId` VARCHAR(191) NULL,
    `smallProjectId` VARCHAR(191) NULL,
    `client` VARCHAR(191) NULL,
    `project` VARCHAR(191) NULL,
    `engineerInCharge` VARCHAR(191) NULL,
    `fieldTestsDetail` VARCHAR(191) NULL,
    `technicianInCharge` VARCHAR(191) NULL,
    `startDate` DATETIME(3) NULL,
    `endDate` DATETIME(3) NULL,
    `remarks` VARCHAR(191) NULL,
    `labTestDescription` VARCHAR(191) NULL,
    `agreedDelivery` DATETIME(3) NULL,
    `actualDelivery` DATETIME(3) NULL,
    `signature` VARCHAR(191) NULL,
    `acknowledgement` VARCHAR(191) NULL,
    `reportIssuedBy` VARCHAR(191) NULL,
    `reportDeliveredTo` VARCHAR(191) NULL,
    `contact` VARCHAR(191) NULL,
    `dateTime` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
